import cv2 as cv
import matplotlib.pyplot as plt 


img_real = cv.imread('data/foto-HL-28.jpg', 0)

cv.imshow('img', img_real)
cv.waitKey(0)
cv.destroyAllWindows()
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.imshow('Edges', edges)
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.waitKey(0)
cv.destroyAllWindows()
cv.imshow('Edges', edges)
cv.waitKey(0)
cv.destroyAllWindows()
